from __future__ import annotations

import secrets
from typing import Any

from fastapi import APIRouter, Header, HTTPException
from pydantic import BaseModel, Field

from api.main import current_user_from_token, require_api_key, role_to_key
from core.auth import set_user_password, verify_password
from core.db import DB_PATH, fetchall, fetchone, get_conn, now_iso

router = APIRouter(prefix="/api/v1")


class ChangePasswordRequest(BaseModel):
    current_password: str = Field(..., min_length=1)
    new_password: str = Field(..., min_length=8)


class ToggleUserActiveRequest(BaseModel):
    active: bool


def require_user(authorization: str | None, x_api_key: str | None) -> dict[str, Any]:
    require_api_key(x_api_key)
    return current_user_from_token(authorization)


def require_owner(authorization: str | None, x_api_key: str | None) -> dict[str, Any]:
    user = require_user(authorization, x_api_key)
    if user.get("role_key") != "owner":
        raise HTTPException(status_code=403, detail="Owner access required.")
    return user


def public_app_user(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": row.get("id"),
        "display_name": row.get("display_name") or "",
        "role": row.get("role") or "Staff",
        "role_key": role_to_key(row.get("role")),
        "active": int(row.get("active") or 0),
        "must_change_password": int(row.get("must_change_password") or 0),
        "last_login_at": row.get("last_login_at"),
        "created_at": row.get("created_at"),
    }


@router.post("/auth/change-password")
def change_password(
    payload: ChangePasswordRequest,
    authorization: str | None = Header(default=None, alias="Authorization"),
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> dict[str, Any]:
    user = require_user(authorization, x_api_key)
    conn = get_conn(DB_PATH)
    try:
        row = fetchone(conn, "SELECT * FROM app_users WHERE id=? AND active=1", (user.get("id"),))
        if not row:
            raise HTTPException(status_code=401, detail="User no longer exists or is inactive.")
        if not verify_password(payload.current_password, row.get("password_hash")):
            raise HTTPException(status_code=400, detail="Current password is incorrect.")
        if len(payload.new_password) < 8:
            raise HTTPException(status_code=422, detail="Use at least 8 characters.")
        set_user_password(conn, int(row["id"]), payload.new_password, must_change=False)
        conn.execute(
            "UPDATE app_users SET last_login_at=COALESCE(last_login_at, ?) WHERE id=?",
            (now_iso(), row["id"]),
        )
        conn.commit()
        return {"ok": True, "message": "Password changed."}
    finally:
        conn.close()


@router.get("/users")
def list_users(
    authorization: str | None = Header(default=None, alias="Authorization"),
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> dict[str, Any]:
    require_owner(authorization, x_api_key)
    conn = get_conn(DB_PATH)
    try:
        rows = fetchall(
            conn,
            """
            SELECT id, display_name, role, active, must_change_password, last_login_at, created_at
            FROM app_users
            ORDER BY active DESC, role, display_name
            """,
        )
        return {"ok": True, "items": [public_app_user(row) for row in rows]}
    finally:
        conn.close()


@router.post("/users/{user_id}/reset-password")
def reset_user_password(
    user_id: int,
    authorization: str | None = Header(default=None, alias="Authorization"),
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> dict[str, Any]:
    owner = require_owner(authorization, x_api_key)
    temporary_password = f"HO-{secrets.token_urlsafe(9)}"
    conn = get_conn(DB_PATH)
    try:
        row = fetchone(conn, "SELECT * FROM app_users WHERE id=?", (user_id,))
        if not row:
            raise HTTPException(status_code=404, detail="User not found.")
        set_user_password(conn, user_id, temporary_password, must_change=True)
        return {
            "ok": True,
            "temporary_password": temporary_password,
            "user": public_app_user({**row, "must_change_password": 1}),
            "message": f"Temporary password generated by {owner.get('display_name')}. Show it once and ask the user to change it.",
        }
    finally:
        conn.close()


@router.post("/users/{user_id}/active")
def set_user_active(
    user_id: int,
    payload: ToggleUserActiveRequest,
    authorization: str | None = Header(default=None, alias="Authorization"),
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> dict[str, Any]:
    owner = require_owner(authorization, x_api_key)
    if int(owner.get("id") or 0) == user_id and not payload.active:
        raise HTTPException(status_code=409, detail="You cannot deactivate your own signed-in owner account.")
    conn = get_conn(DB_PATH)
    try:
        row = fetchone(conn, "SELECT * FROM app_users WHERE id=?", (user_id,))
        if not row:
            raise HTTPException(status_code=404, detail="User not found.")
        conn.execute("UPDATE app_users SET active=? WHERE id=?", (1 if payload.active else 0, user_id))
        conn.commit()
        updated = fetchone(conn, "SELECT * FROM app_users WHERE id=?", (user_id,)) or {}
        return {"ok": True, "user": public_app_user(updated)}
    finally:
        conn.close()
